### PR TITLE
Fixes #116

### LINKED ISSUE #116: edit title bug
Given the following entries:
- 1 AAA #tag1
- 2 BBB

Run "edit 1 title/BBB"

### PR DESCRIPTION
**Pull request by karen**

### CODE REVIEW

**Comment by bertoia** [comment]
Still doesn't work for the situation in #116

**Comment by karen** [comment]
You want to remove the tags as well or something? It no longer shows the duplicate task error message. I'm not sure what's the expected behaviour.

I think it has always been the original behaviour of edit to not remove the user's tags if no tags are specified in the `edit` command. Otherwise, we'd have to add a flag or the user would have to relist out all tags in the existing task, which would be pretty annoying.

**Comment by bertoia** [comment]
My bad. The example in #116 wasn't correct.
should be as such:

Given the following entries:
- 1 AAA #tag1
- 2 BBB

Run "edit 1 title/BBB"

The expected state would be
- 1 BBB #tag1
- 2 BBB

**Comment by karen** [comment]
Done

**Review by bertoia — APPROVED** [review]

**Pull request merged**
